---
- name: Save user data
  agnosticd_user_info:
    user: user1
    data:
      openshift_cluster_ingress_domain: "{{ openshift_cluster_ingress_domain }}"
      openshift_console_url: "{{ openshift_console_url }}"
      openshift_password: "{{ openshift_password }}"
      openshift_user: "{{ openshift_user }}"
      openshift_user_admin: "{{ openshift_user_admin }}"
