---
- name: Save user data
  agnosticd_user_info:
    user: user1
    data:
      openshift_cluster_ingress_domain: "{{ openshift_cluster_ingress_domain }}"
      openshift_console_url: "{{ openshift_console_url }}"
      openshift_user: "user1"

- name: Deploy Showroom
  ansible.builtin.include_role:
    name: ocp4_workload_showroom
