---
- name: Save user data
  agnosticd_user_info:
    user: user1
    data:
      fruit: "apple"
      cluster_apps_domain: "{{ openshift_cluster_ingress_domain }}"
      openshift_console_url: "{{ openshift_console_url }}"
