---
- name: Install openshift and kubernetes Python packages
  command: /usr/libexec/platform-python -m pip install openshift kubernetes==33.1.0
  
- name: Create dynamic-plugins-npmrc Secret in OpenShift
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: dynamic-plugins-npmrc
        namespace: default
      type: Opaque
      data:
        .npmrc: "{{ '@redhat:registry=https://npm.registry.redhat.com' | b64encode }}"
